-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- ALTER TABLE public.organizations
-- ADD COLUMN created_by uuid REFERENCES auth.users(id);
